require('dotenv').config({ path: '.env' });
const mongoose = require('mongoose');
const User = require('../src/models/User');
const Issue = require('../src/models/Issue');
const bcrypt = require('bcryptjs');

const seedData = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB Connected for Seeding');

        // Clear existing data (Optional: Remove if you want to keep existing)
        // await User.deleteMany({});
        // await Issue.deleteMany({});

        // 1. Create/Ensure Admin
        const adminEmail = 'admin@civicsense.gov';
        let admin = await User.findOne({ email: adminEmail });
        if (!admin) {
            const salt = await bcrypt.genSalt(10);
            const hashedPassword = await bcrypt.hash('admin123', salt);
            admin = await User.create({
                name: 'Super Admin',
                email: adminEmail,
                password: hashedPassword,
                role: 'admin',
                isActive: true
            });
            console.log('Admin user created');
        }

        // 2. Create Dummy Issues
        const issueCount = await Issue.countDocuments();
        if (issueCount < 5) {
            console.log('Seeding Issues...');
            const statuses = ['Open', 'In Progress', 'Resolved', 'Rejected'];
            const categories = ['Pothole', 'Garbage', 'Water Leak', 'Streetlight'];
            const priorities = ['Low', 'Medium', 'High', 'Critical'];

            const issues = [];
            for (let i = 0; i < 20; i++) {
                issues.push({
                    title: `Seeded Issue ${i + 1}`,
                    description: 'This is a test issue generated by the seeder.',
                    category: categories[Math.floor(Math.random() * categories.length)],
                    priority: priorities[Math.floor(Math.random() * priorities.length)],
                    status: statuses[Math.floor(Math.random() * statuses.length)],
                    location: {
                        lat: 28.6139 + (Math.random() * 0.01),
                        lng: 77.2090 + (Math.random() * 0.01),
                        address: 'New Delhi, India'
                    },
                    imageUrl: 'https://via.placeholder.com/300',
                    reportedBy: admin._id,
                    createdAt: new Date(new Date().setDate(new Date().getDate() - Math.floor(Math.random() * 365))) // Random date last year
                });
            }
            await Issue.insertMany(issues);
            console.log('20 Issues Seeded');
        } else {
            console.log('Issues already exist, skipping seed.');
        }

        console.log('Seeding Complete');
        process.exit();
    } catch (error) {
        console.error('Seeding Error:', error);
        process.exit(1);
    }
};

seedData();
